### ISSUE TITLE
Beautifulsoup append 純文字 bug

### ISSUE THREAD

**Issue by niauah** [i3thuan5/SuiSiann-KauTui#311]
```py
    for i, phiau_tag in enumerate(parser.p.contents):
        # 這个content是純文字
        if phiau_tag.name is None:
            sin_html.p.append(phiau_tag.string)
        else:
            # ...
```
輸入ê兩詞中央有空白ê時陣 
```html
<p><span class="lui-1">Hit</span> <span class="lui-2">lō</span></p>
```

`append(phiau_tag.string)` 會造成for loop減走一个，毋知影是siánn原因
改做`append(str(phiau_tag))` 才會使

（兩个type無kâng，`phiau_tag.string`是 `NavigableString`）
https://www.crummy.com/software/BeautifulSoup/bs4/doc/index.html?highlight=new_tag#navigablestring

**Comment by niauah** [comment]
#309

**Comment by sih4sing5hong5** [comment]
看起來處理好勢--ah？
