### ISSUE TITLE
Python subtitle editor 

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/SuiSiann-KauTui#331]
https://github.com/otsaloma/gaupol
![圖片](https://user-images.githubusercontent.com/6355592/128833574-95e60575-ec81-4fc4-bec3-818808d4d847.png)

https://gitlab.com/mgoral/subconvert
![圖片](https://user-images.githubusercontent.com/6355592/128834053-696c246b-552b-4571-ad95-d489b43a2aff.png)

**Comment by sih4sing5hong5** [comment]
攏是桌面系統--ê，咱ài網頁js版--ê
