### ISSUE TITLE
改用 multiple-databases-backup專案來備份資料庫 

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/SuiSiann-KauTui#372]
### 變更原因

發覺[PiHun-Docker-Postgres](https://github.com/i3thuan5/PiHun-Docker-Postgres)設計有問題，一直有人bô備份tio̍h，所以愛修改tshuē container ê方式，改做用label來tshuē。
全部postgres container攏加label`backup.postgres=true`，備份script用label來tshuē，親像：
```
$ docker container list --filter label=backup.postgres=true
```

### 變更時間

3/1~3/17加label、改script、上線。

### 需求

資料備份管理程序 ê 資料備份策略，講正式資料庫以外，應該ài koh有2位ê異地備份。

#### 機密

1. script本身iu-guân bô kā備份檔加密，機密bô變化。

#### 完整

1. script用pg_dump，應該bô影響。

#### 可用

1. docker-compose up -d，服務停10秒內，較bô風險
2. 本底 [PiHun-Docker-Postgres](https://github.com/i3thuan5/PiHun-Docker-Postgres) script會繼續用，kah [multiple-databases-backup](https://github.com/i3thuan5/multiple-databases-backup) tâng-tsê備份。

### 解決做法Github連結

1. 備份Script本底是 PiHun-Docker-Postgres 改做 multiple-databases-backup 來做，備份Script PR：https://github.com/i3thuan5/multiple-databases-backup/pull/1
2. 資料庫container加label，本身PR： #373 

### 未來規劃

等 [multiple-databases-backup](https://github.com/i3thuan5/multiple-databases-backup) 過1個月穩定，才kā [PiHun-Docker-Postgres](https://github.com/i3thuan5/PiHun-Docker-Postgres) 擋--起-來。

### 審查意見

**Comment by a8568730** [comment]
## 審查意見

無問題。
