### ISSUE TITLE
對 pabuy.ithuan.tw suá到 diong.ithuan.tw

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/SuiSiann-KauTui#374]
## 變更原因
Kā 服務對 pabuy.ithuan.tw suá到 diong.ithuan.tw，而且加CD。

## 變更時間
2023.5.12～2023.5.31

## 需求
因為pabuy.ithuan.tw想欲關起來，服務集中，主機較好huānn。

### 機密

1. 需要lia̍h資料庫，匯到 diong.ithuan.tw。

### 完整

Bô完整先問題

### 可用

1. 會先用 ithoan.tw 來試，試ê時陣袂影響tio̍h線頂服務
2. Suá服務ê時，會停2點鐘。

## 解決做法Github連結

Ah-bē好。

## 未來規劃

Bô。

**Comment by a8568730** [comment]
## 審查意見

好。
